# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2', models.CharField(max_length=2, unique=True, verbose_name='alpha-2 code')),
                ('alpha3', models.CharField(max_length=3, unique=True, verbose_name='alpha-3 code')),
                ('numeric', models.CharField(max_length=3, verbose_name='numeric code')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=75, populate_from='name', unique=True, verbose_name='slug')),
                ('official_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='official name')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'ISO 3166 country',
                'verbose_name_plural': 'ISO 3166 countries',
            },
        ),
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=45, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mailingaddress.ISOCountry')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mailingaddress',
            unique_together=set([('address_line1', 'address_line2', 'postal_code', 'city', 'state_province', 'country')]),
        ),
    ]
