# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_vendor_addresses'),
        ('django_mailingaddress', '0002_auto_20160821_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingaddress',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Vendor'),
        ),
    ]
