# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailingaddress', '0003_mailingaddress_vendor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailingaddress',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mailingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mailingaddress',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='MailingAddress',
        ),
    ]
