# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:37
from __future__ import unicode_literals

import catalog.forms
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Three-Character', max_length=3, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('gtin_id', models.CharField(blank=True, default='', help_text='Global Trade Item Number', max_length=15, validators=[catalog.forms.validate_gtin], verbose_name='GTIN')),
                ('mpn_id', models.CharField(blank=True, default='', help_text="Manufacturer's Part Number", max_length=64, verbose_name='MPN')),
                ('asin_id', models.CharField(blank=True, default='', help_text='Amazon Standard ID Number', max_length=10, verbose_name='ASIN')),
                ('barcode_pdf417', models.ImageField(blank=True, null=True, upload_to='product_pdf417/')),
                ('weight_product', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Ounces', max_digits=10, verbose_name='Product Weight')),
                ('weight_shipping', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Ounces', max_digits=10, verbose_name='Shipping Weight')),
                ('dimension_height', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Height')),
                ('dimension_width', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Width')),
                ('dimension_depth', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Depth')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Three-Character', max_length=3, verbose_name='Code')),
                ('gtin_id', models.CharField(blank=True, default='', help_text='Global Idenfiier.', max_length=15, verbose_name='GTIN')),
                ('mpn_id', models.CharField(blank=True, default='', help_text="Manufacturer's Part Number", max_length=64, verbose_name='MPN')),
                ('asin_id', models.CharField(blank=True, default='', help_text='Amazon Standard ID Number', max_length=10, verbose_name='ASIN')),
                ('barcode_pdf417', models.ImageField(blank=True, null=True, upload_to='product_pdf417/')),
                ('weight_product', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Ounces', max_digits=10, verbose_name='Product Weight')),
                ('weight_shipping', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Ounces', max_digits=10, verbose_name='Shipping Weight')),
                ('dimension_height', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Height')),
                ('dimension_width', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Width')),
                ('dimension_depth', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='In Inches', max_digits=10, verbose_name='Product Depth')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Two-Characters', max_length=2, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Vendor'),
        ),
    ]
