# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailingaddress', '0002_auto_20160821_1045'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mailingaddress.MailingAddress'),
        ),
    ]
