# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vendor_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='addresses',
        ),
    ]
