# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160814_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='abbr',
            field=models.CharField(default='', max_length=2, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='abbr',
            field=models.CharField(default='', max_length=2, verbose_name='Abbreviation'),
        ),
    ]
