# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_vendor_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='reg_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Local Registration Number'),
        ),
    ]
