# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160814_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='abbr',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='abbr',
        ),
        migrations.AddField(
            model_name='brand',
            name='code',
            field=models.CharField(default='', max_length=2, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='code',
            field=models.CharField(default='', max_length=2, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Vendor'),
        ),
    ]
