# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160815_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='gtin_id',
            field=models.CharField(blank=True, default='', help_text='Global Idenfiier.', max_length=15, verbose_name='GTIN'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mpn_id',
            field=models.CharField(blank=True, default='', help_text="Manufacturer's Part Number", max_length=64, verbose_name='MPN'),
        ),
    ]
