# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 08:14
from __future__ import unicode_literals

import catalog.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160816_0428'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin_id',
            field=models.CharField(blank=True, default='', help_text='Global Trade Item Number', max_length=15, validators=[catalog.forms.validate_gtin], verbose_name='GTIN'),
        ),
    ]
