# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160817_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin_id',
            field=models.CharField(blank=True, default='', help_text='Amazon Standard ID Number', max_length=10, verbose_name='ASIN'),
        ),
    ]
