# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailingaddress', '0004_auto_20160821_1131'),
        ('catalog', '0005_auto_20160821_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='phone_number',
            new_name='tel_voice',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line1',
            field=models.CharField(blank=True, max_length=45, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_line2',
            field=models.CharField(blank=True, max_length=45, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mailingaddress.ISOCountry'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state_province',
            field=models.CharField(blank=True, max_length=40, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tel_fax',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
