# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_auto_20160814_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Three-Character', max_length=3, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Two-Characters', max_length=2, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Vendor'),
        ),
    ]
