# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160814_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('code', models.CharField(default='', help_text='Three-Character', max_length=3, verbose_name='Code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'verbose_name': 'Variant',
            },
        ),
    ]
