# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode_pdf417',
            field=models.ImageField(null=True, upload_to='product_pdf417/'),
        ),
    ]
