# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productvariant_barcode_pdf417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='barcode_pdf417',
            field=models.ImageField(blank=True, null=True, upload_to='product_pdf417/'),
        ),
    ]
